# Generated by Django 2.2 on 2022-03-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='create_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='creation_date',
        ),
    ]
