# Generated by Django 2.2 on 2022-03-31 18:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20220331_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=90, verbose_name='User')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation_date')),
                ('comment', ckeditor.fields.RichTextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Opinion',
                'verbose_name_plural': 'Opinions',
            },
        ),
    ]
