# Generated by Django 2.2 on 2022-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='cellphone',
            field=models.IntegerField(default=1, verbose_name='Cellphone'),
            preserve_default=False,
        ),
    ]
