# Generated by Django 2.2 on 2022-04-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20220331_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
